### PR TITLE
test: add fuzz testing for `BitReader` and `BitWriter`

### PR DESCRIPTION
**Pull request by eventualbuddha**
Something I wanted to do when I was writing these initially, just to ensure a high degree of confidence in these basic classes.

Here's an example of a failure:

image

And the diff that caused it:

```diff
diff --git a/src/bits/BitReader.ts b/src/bits/BitReader.ts
index ec24f65..95070c4 100644
--- a/src/bits/BitReader.ts
+++ b/src/bits/BitReader.ts
@@ -73,7 +73,7 @@ export default class BitReader {
     }
 
     // Fall back to reading bits individually.
-    let result = 0
+    let result = 1
 
     for (const mask of makeMasks(sizeofUint)) {
       const bit = this.readUint1()
```

### CODE REVIEW

**Comment by benadida** [comment]
my suggestion on tests that use randomness: run them separate from CI, as they don't consistently give the same answer, so it doesn't fully match the CI paradigm. That said, I don't have a good answer for when to run them. Is there a way to make this a separate CI test job?

**Comment by eventualbuddha** [comment]
> I don't have a good answer for when to run them. Is there a way to make this a separate CI test job?

[This](https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow) seems to imply that you can set up a scheduled workflow, but if you schedule a workflow on a branch then CircleCI won't build on commits for that branch. We could in theory work around this by having the `master` build push to another branch that then is run on a schedule.

That said, I think the odds that these tests will pass locally and fail randomly on CI is pretty low. I'd rather take the risk and disable them if needed.

**Comment by eventualbuddha** [comment]
> That said, I think the odds that these tests will pass locally and fail randomly on CI is pretty low. I'd rather take the risk and disable them if needed.

@benadida thoughts?

**Review by benadida — APPROVED** [review]
Sounds good, let's do this

**Pull request merged**
